import { useMemo, useState } from 'react'
import './styles.css'

const navItems = [
  ['dashboard', 'Overview', '⌂'], ['detect', 'Detect disease', '⌁'], ['climate', 'Climate risk', '◌'],
  ['spread', 'Disease spread', '⌘'], ['location', 'Disease location', '⌖'], ['recommendations', 'Recommendations', '✦'],
  ['alerts', 'Alerts', '⚠'], ['history', 'Diagnosis history', '↺'],
]

const detections = [
  { disease: 'Blister Blight', block: 'B2 · North-East', confidence: '96.4%', severity: 'Moderate', tone: 'red', time: 'Today, 09:42', color: '#d5ead7' },
  { disease: 'Brown Blight', block: 'A3 · Ridge', confidence: '91.8%', severity: 'Mild', tone: 'amber', time: 'Yesterday, 15:18', color: '#e9dfc5' },
  { disease: 'Healthy leaf', block: 'C1 · Lower slope', confidence: '98.1%', severity: 'Healthy', tone: 'green', time: 'Yesterday, 11:06', color: '#c7e2ca' },
]

const blocks = ['A1', 'A2', 'A3', 'A4', 'B1', 'B2', 'B3', 'B4', 'C1', 'C2', 'C3', 'C4', 'D1', 'D2', 'D3', 'D4']
const risks = { A1: 'healthy', A2: 'low', A3: 'watch', A4: 'healthy', B1: 'low', B2: 'critical', B3: 'high', B4: 'watch', C1: 'healthy', C2: 'high', C3: 'watch', C4: 'low', D1: 'healthy', D2: 'low', D3: 'healthy', D4: 'healthy' }
const alerts = [
  { type: 'Critical', title: 'Disease spread warning', body: 'Blister Blight has a 78% probability of spreading from B2 to B3 within 36 hours.', meta: 'B2 → B3 · 12 min ago', tone: 'critical', unread: true },
  { type: 'Climate', title: 'Humidity threshold exceeded', body: 'Relative humidity has stayed above 90% for 6 hours across the North-East division.', meta: 'Climate sensor · 1 hr ago', tone: 'warning', unread: true },
  { type: 'Advisory', title: 'Inspection recommended', body: 'Inspect C2 and B3 during the next field round. Both blocks show elevated risk.', meta: 'AI advisory · Yesterday', tone: 'advisory', unread: false },
]

function LeafVisual({ heatmap = false, className = '' }) {
  return <div className={`leaf-visual ${heatmap ? 'heatmap' : ''} ${className}`} aria-label="Tea leaf preview">
    <span className="leaf-vein" /><span className="leaf-spot spot-one" /><span className="leaf-spot spot-two" /><span className="leaf-spot spot-three" />
    {heatmap && <><span className="heat-zone zone-one" /><span className="heat-zone zone-two" /><span className="heat-zone zone-three" /></>}
  </div>
}

function Badge({ children, tone = 'green' }) { return <span className={`badge ${tone}`}>{children}</span> }
function Stat({ label, value, detail, icon, tone = '' }) { return <div className="stat-card"><div className={`stat-icon ${tone}`}>{icon}</div><div><p>{label}</p><strong>{value}</strong><small>{detail}</small></div></div> }

export function Dashboard({ onNavigate }) {
  return <>
    <section className="hero-panel">
      <div><span className="eyebrow">AI-powered field intelligence</span><h1>Tea Disease<br /><em>Intelligence</em></h1><p>Detect early. Predict spread. Protect every block.</p><div className="hero-actions"><button className="button primary" onClick={() => onNavigate('detect')}>＋ Scan tea leaf</button><button className="button ghost" onClick={() => onNavigate('spread')}>View plantation risk <span>↗</span></button></div></div>
      <div className="hero-orbit"><div className="orbit-ring ring-one" /><div className="orbit-ring ring-two" /><div className="orbit-core"><span>84</span><small>health<br />score</small></div><div className="orbit-label label-top">LIVE<br /><b>MONITORING</b></div><div className="orbit-label label-bottom">Nuwara Eliya<br /><b>1,240 ha</b></div></div>
    </section>
    <div className="stats-grid"><Stat label="Plantation health" value="84%" detail="↑ 3.2% this week" icon="♥" tone="green" /><Stat label="Active disease cases" value="12" detail="4 new today" icon="⌁" tone="red" /><Stat label="High-risk blocks" value="3" detail="B2 needs attention" icon="⌖" tone="amber" /><Stat label="Climate disease risk" value="82%" detail="↑ High risk" icon="◌" tone="lime" /><Stat label="Critical alerts" value="2" detail="Needs action" icon="⚠" tone="red" /><Stat label="Last scan" value="09:42" detail="B2 · Blister Blight" icon="◷" tone="blue" /></div>
    <div className="content-grid">
      <section className="panel risk-panel"><div className="panel-head"><div><span className="eyebrow">Climate fusion model</span><h2>Current disease risk</h2></div><Badge tone="red">High risk</Badge></div><div className="risk-main"><div className="risk-number">82<small>%</small></div><div><h3>Blister Blight</h3><p>High humidity and recent rainfall are creating favourable conditions for development.</p></div></div><div className="metric-row"><div><span>Humidity</span><b>91%</b></div><div><span>Rainfall</span><b>18 mm</b></div><div><span>Temperature</span><b>23.8°C</b></div><div><span>Trend</span><b className="positive">↑ 12%</b></div></div><div className="progress-line"><i style={{ width: '82%' }} /></div><button className="text-button" onClick={() => onNavigate('climate')}>Open climate analysis <span>→</span></button></section>
      <section className="panel blocks-panel"><div className="panel-head"><div><span className="eyebrow">Spatial overview</span><h2>Plantation risk overview</h2></div><button className="icon-button" onClick={() => onNavigate('spread')} aria-label="Open spread prediction">↗</button></div><div className="mini-map">{blocks.map(block => <button key={block} className={`block-tile ${risks[block]}`} onClick={() => onNavigate('location')} aria-label={`${block} ${risks[block]} risk`}><b>{block}</b><span /></button>)}</div><div className="legend"><span><i className="dot healthy" />Healthy</span><span><i className="dot watch" />Watch</span><span><i className="dot high" />High</span><span><i className="dot critical" />Critical</span></div></section>
    </div>
    <section className="panel detections-panel"><div className="panel-head"><div><span className="eyebrow">Latest field observations</span><h2>Recent disease detections</h2></div><button className="text-button" onClick={() => onNavigate('history')}>View all history <span>→</span></button></div><div className="detection-list">{detections.map(item => <div className="detection-row" key={item.time}><LeafVisual className="thumb" /><div className="disease-name"><b>{item.disease}</b><small>{item.block}</small></div><div><small>Confidence</small><strong>{item.confidence}</strong></div><Badge tone={item.tone}>{item.severity}</Badge><small className="detection-time">{item.time}</small><button className="row-more" aria-label={`View ${item.disease}`}>•••</button></div>)}</div></section>
  </>
}

export function Detection({ onResult }) {
  const [file, setFile] = useState(null); const [loading, setLoading] = useState(false)
  const choose = event => { const picked = event.target.files?.[0]; if (picked) setFile(URL.createObjectURL(picked)) }
  const analyze = () => { setLoading(true); window.setTimeout(() => { setLoading(false); onResult() }, 1300) }
  return <section className="workflow-grid"><div><span className="eyebrow">Multimodal diagnosis</span><h1 className="page-title">AI Tea Leaf<br /><em>Disease Detection</em></h1><p className="lede">Upload a clear leaf image and combine visual symptoms with local climate signals for a faster field decision.</p><div className={`upload-box ${file ? 'has-file' : ''}`}>{file ? <><LeafVisual heatmap className="upload-preview" /><button className="remove-file" onClick={() => setFile(null)}>×</button><div className="upload-success"><Badge>Image ready</Badge><span>leaf-sample.jpg · JPG</span></div></> : <><div className="upload-icon">⌁</div><h3>Drop a tea leaf image here</h3><p>or use your device camera</p><label className="button primary browse-button">Browse device<input type="file" accept="image/png,image/jpeg" onChange={choose} /></label><button className="button ghost camera-button" onClick={() => setFile('mock-camera')}>◉ Capture from camera</button><small>Supported formats: JPG, PNG · Max 10 MB</small></>}</div><button className="button analyze-button" disabled={!file || loading} onClick={analyze}>{loading ? 'Analyzing tea leaf…' : 'Analyze disease  →'}</button>{loading && <div className="analysis-steps"><span className="spinner" /><div><b>Processing climate-aware diagnosis</b><small>Detecting leaf region · Extracting symptoms · Fusing climate features</small></div></div>}</div><aside className="sample-card"><div className="panel-head"><h2>Sample information</h2><span className="optional">Optional</span></div><label>Plantation<select><option>Green Valley Tea Estate</option><option>Horton Plains Estate</option></select></label><label>Block<select><option>B2 · North-East</option><option>B3 · Upper slope</option><option>A3 · Ridge</option></select></label><label>Collection date<input type="date" defaultValue="2026-08-26" /></label><label>Field notes<textarea placeholder="Add observations from the field…" /></label><div className="privacy-note">⌾ <span>Images stay in this prototype session and are not uploaded.</span></div></aside></section>
}

export function Diagnosis({ onNavigate }) { return <><div className="result-banner"><div><span className="eyebrow">Analysis complete · 09:42 today</span><h1 className="page-title">Blister Blight <Badge tone="red">High risk</Badge></h1><p>Detected in B2 · North-East section with climate conditions favourable for spread.</p></div><button className="button primary" onClick={() => onNavigate('recommendations')}>View treatment plan →</button></div><div className="diagnosis-grid"><section className="panel image-result"><LeafVisual heatmap className="large-leaf" /><div className="image-caption"><span>Leaf sample · B2</span><span>Grad-CAM++ overlay</span></div></section><section className="panel score-panel"><div className="score-ring"><div><strong>96.4</strong><small>% confidence</small></div></div><div className="score-details"><div><span>Severity</span><Badge tone="amber">Moderate</Badge></div><div><span>Affected area</span><b>34%</b></div><div><span>Estimated spread risk</span><b className="danger-text">78%</b></div></div></section></div><div className="content-grid diagnosis-bottom"><section className="panel"><div className="panel-head"><div><span className="eyebrow">Explainable AI</span><h2>Why was this predicted?</h2></div><span className="gradcam-mark">Grad-CAM++</span></div><p className="explain-copy">Highlighted regions represent the areas that contributed most strongly to the AI diagnosis.</p><div className="indicator-list"><div><i>◈</i><span><b>Circular translucent lesions</b><small>Strong visual signal detected</small></span><b>94%</b></div><div><i>◌</i><span><b>High humidity</b><small>91% relative humidity</small></span><b>89%</b></div><div><i>≋</i><span><b>Recent rainfall</b><small>18 mm in the last 24 hours</small></span><b>84%</b></div></div></section><section className="panel severity-card"><span className="eyebrow">Severity assessment</span><h2>Moderate <Badge tone="amber">46% affected</Badge></h2><div className="severity-scale"><i /><i /><i className="active" /><i /><i /></div><div className="severity-labels"><span>Healthy</span><span>Mild</span><span>Moderate</span><span>Severe</span><span>Critical</span></div><p>Action is recommended within the next <b>24–48 hours</b> to reduce further spread.</p></section></div></> }

export function Climate() { const forecast = [45, 51, 65, 76, 84, 80, 68]; return <><div className="page-heading"><div><span className="eyebrow">Multimodal climate fusion</span><h1 className="page-title">Climate-Aware <em>Disease Risk</em></h1><p className="lede">Environmental signals translated into a clear disease outlook for every field team.</p></div><Badge tone="red">Risk elevated</Badge></div><div className="climate-grid"><section className="panel climate-score"><span className="eyebrow">Current risk score</span><div className="gauge"><div><strong>82%</strong><small>HIGH</small></div></div><h3>Blister Blight</h3><p>Risk expected to peak Friday as humidity and rainfall persist.</p></section><section className="panel factors"><div className="panel-head"><h2>Climate factors driving risk</h2><span>Updated 10 min ago</span></div>{[['Humidity','91%','Strong influence','91%','red'],['Rainfall','18 mm','High influence','74%','amber'],['Temperature','23.8°C','Favourable','62%','green'],['Solar radiation','Low','Moderate influence','38%','blue']].map(f => <div className="factor" key={f[0]}><div><b>{f[0]}</b><span>{f[1]} · {f[2]}</span></div><div className="factor-bar"><i className={f[4]} style={{ width: f[3] }} /></div><strong>{f[3]}</strong></div>)}</section></div><section className="panel forecast"><div className="panel-head"><div><span className="eyebrow">Outlook</span><h2>7-day disease risk forecast</h2></div><span className="forecast-note">● Predicted outbreak window</span></div><div className="chart">{forecast.map((value, index) => <div className="chart-day" key={value}><span>{value}%</span><div className={`bar ${value > 75 ? 'outbreak' : ''}`} style={{ height: `${value * 1.55}px` }} /><small>{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][index]}</small></div>)}</div><div className="insight"><span>✦</span><p><b>AI insight</b> Disease risk is expected to peak on Friday due to sustained humidity and rainfall.</p></div></section></> }

export function Spread({ onNavigate }) { const [time, setTime] = useState('Now'); const levels = time === 'Now' ? risks : { ...risks, B3: time === '+24h' ? 'critical' : 'critical', C2: time === '+48h' ? 'critical' : 'high', C3: time === '7 Days' ? 'high' : 'watch', B4: time === '7 Days' ? 'high' : 'watch' }; return <><div className="page-heading"><div><span className="eyebrow">Research model concept · GCN + LSTM</span><h1 className="page-title">Disease Spread <em>Prediction</em></h1><p className="lede">See where the next risk may emerge, then turn the forecast into a field inspection plan.</p></div><Badge tone="red">78% spread probability</Badge></div><div className="spread-layout"><section className="panel spread-map"><div className="panel-head"><div><h2>Green Valley plantation</h2><span>16 monitored blocks · 1,240 hectares</span></div><span className="map-live">● Live model</span></div><div className="timeline">{['Now','+24h','+48h','+72h','7 Days'].map(t => <button className={time === t ? 'active' : ''} onClick={() => setTime(t)} key={t}>{t}</button>)}</div><div className="spread-grid">{blocks.map(block => <button key={block} className={`spread-block ${levels[block]}`} onClick={() => onNavigate('location')}><b>{block}</b><span>{levels[block]}</span></button>)}<div className="route route-one">B2 <span>→</span> B3</div><div className="route route-two">B2 <span>↘</span> C2</div></div><div className="legend spread-legend"><span><i className="dot healthy" />Healthy</span><span><i className="dot watch" />Watch</span><span><i className="dot high" />High</span><span><i className="dot critical" />Critical</span></div></section><aside className="spread-aside"><section className="panel"><span className="eyebrow">Spread intelligence</span><div className="spread-facts"><div><span>Source block</span><b>B2</b></div><div><span>Disease</span><b>Blister Blight</b></div><div><span>Predicted next</span><b className="danger-text">B3</b></div><div><span>Estimated time</span><b>24–36 hrs</b></div><div><span>Main driver</span><b>Humidity + wind</b></div></div></section><section className="panel containment"><span className="eyebrow">AI containment strategy</span><h2>Protect B3 first</h2><ul><li>Prioritise inspection of B3</li><li>Establish a monitoring zone around B2</li><li>Treat B2 before the spread threshold</li><li>Inspect C2 at increased frequency</li></ul><button className="button primary full" onClick={() => onNavigate('recommendations')}>Create field action plan →</button></section></aside></div></> }

function Location() { return <><div className="page-heading"><div><span className="eyebrow">GIS field intelligence</span><h1 className="page-title">Disease Location <em>Intelligence</em></h1><p className="lede">A precise field handoff from AI detection to the team on the ground.</p></div><div className="hero-actions"><button className="button ghost">⌖ Navigate to block</button><button className="button primary">＋ Assign inspection</button></div></div><div className="location-grid"><section className="panel plantation-map"><div className="map-surface"><div className="map-lines" /><span className="map-pin pin-b2">B2</span><span className="map-pin pin-b3">B3</span><span className="map-pin pin-c2">C2</span><div className="map-compass">N<br /><b>＋</b></div></div><div className="map-caption"><div><span className="eyebrow">Affected location</span><h2>Block B2 · North-East section</h2><p>Green Valley Tea Estate · Nuwara Eliya</p></div><Badge tone="red">Critical hotspot</Badge></div></section><section className="panel location-facts"><span className="eyebrow">Field record</span>{[['Division','North-East'],['Section','B2 / Row 14–22'],['Approx. GPS','6.9497° N, 80.7891° E'],['Disease','Blister Blight'],['Severity','Moderate · 46%'],['Detected','26 Aug 2026 · 09:42']].map(row => <div key={row[0]}><span>{row[0]}</span><b>{row[1]}</b></div>)}</section></div><section className="panel hotspots"><div className="panel-head"><div><span className="eyebrow">Concentration analysis</span><h2>Infection hotspots</h2></div><span>3 zones identified</span></div><div className="hotspot-list">{[['B2 North-East','Critical','red'],['B2 Central','High','amber'],['B3 West','Watch','green']].map(row => <div key={row[0]}><span className={`hotspot-dot ${row[2]}`} /><b>{row[0]}</b><span className="hotspot-bar"><i style={{ width: row[1] === 'Critical' ? '92%' : row[1] === 'High' ? '67%' : '34%' }} /></span><Badge tone={row[2]}>{row[1]}</Badge></div>)}</div></section></> }

function Recommendations() { return <><div className="page-heading"><div><span className="eyebrow">Field action plan</span><h1 className="page-title">Treatment <em>Recommendation</em></h1><p className="lede">Practical next steps for Blister Blight detected in B2.</p></div><Badge>Prototype plan</Badge></div><div className="recommendation-grid"><section className="panel actions"><div className="panel-head"><h2>Recommended immediate actions</h2><span>Priority: today</span></div>{['Isolate affected plants if practical','Remove heavily infected leaves','Inspect nearby tea bushes','Avoid unnecessary overhead irrigation','Monitor neighbouring blocks'].map((action, i) => <div className="action-row" key={action}><span>0{i + 1}</span><b>{action}</b><button aria-label={`Complete ${action}`}>○</button></div>)}</section><section className="panel treatment"><span className="eyebrow">Disease control treatment</span><h2>Targeted fungicide application</h2><div className="treatment-fields"><div><span>Category</span><b>Protective fungicide</b></div><div><span>Target disease</span><b>Blister Blight</b></div><div><span>Application</span><b>Follow product label</b></div><div><span>Frequency</span><b>Authority guidance</b></div></div><div className="safety">⚠ <p><b>Safety notice</b> Use only products approved by the Tea Research Institute or relevant agricultural authority. Follow the product label and PPE requirements.</p></div><div className="alt-controls"><b>Alternative control methods</b><span>Cultural control · Sanitation · Moisture management · Biological options</span></div><div className="hero-actions"><button className="button primary">Save treatment plan</button><button className="button ghost">↓ Download recommendation</button></div></section></div><div className="disclaimer">ⓘ <b>Prototype recommendation only.</b> Final chemical selection, dosage and application must follow approved Tea Research Institute / agricultural authority guidance and product labels.</div></> }

function Alerts() { const [filter, setFilter] = useState('All'); const [items, setItems] = useState(alerts); const visible = items.filter(a => filter === 'All' || a.type === filter || (filter === 'Disease' && a.type === 'Critical') || (filter === 'Spread' && a.type === 'Critical')); return <><div className="page-heading"><div><span className="eyebrow">Action queue</span><h1 className="page-title">Early Warning <em>& Alerts</em></h1><p className="lede">Stay ahead of disease conditions across Green Valley Tea Estate.</p></div><Badge tone="red">2 unread</Badge></div><div className="filter-row">{['All','Critical','Climate','Disease','Spread'].map(item => <button className={filter === item ? 'active' : ''} onClick={() => setFilter(item)} key={item}>{item}</button>)}</div><section className="alert-list">{visible.map(alert => <article className={`alert-card ${alert.unread ? 'unread' : ''}`} key={alert.title}><div className={`alert-symbol ${alert.tone}`}>{alert.tone === 'critical' ? '⚠' : alert.tone === 'warning' ? '◌' : '✦'}</div><div className="alert-copy"><div><Badge tone={alert.tone === 'critical' ? 'red' : alert.tone === 'warning' ? 'amber' : 'green'}>{alert.type}</Badge><span>{alert.meta}</span></div><h2>{alert.title}</h2><p>{alert.body}</p><div className="alert-actions"><button onClick={() => setItems(items.map(item => item === alert ? { ...item, unread: false } : item))}>{alert.unread ? 'Mark as read' : 'Read'}</button><button>View analysis →</button><button>View affected block</button></div></div><span className={`unread-dot ${alert.unread ? '' : 'hidden'}`} /></article>)}</section></> }

function History() { const [query, setQuery] = useState(''); const filtered = detections.filter(d => d.disease.toLowerCase().includes(query.toLowerCase()) || d.block.toLowerCase().includes(query.toLowerCase())); return <><div className="page-heading"><div><span className="eyebrow">Field records</span><h1 className="page-title">Diagnosis <em>History</em></h1><p className="lede">A searchable record of AI-assisted leaf assessments.</p></div><button className="button ghost">↓ Export records</button></div><div className="history-toolbar"><label className="search-field">⌕<input placeholder="Search disease or block" value={query} onChange={e => setQuery(e.target.value)} /></label><select><option>All severity</option><option>Moderate</option><option>Mild</option></select><button className="button ghost">Filter by date ▾</button></div><section className="panel history-table"><div className="table-head"><span>Sample</span><span>Diagnosis</span><span>Location</span><span>Confidence</span><span>Severity</span><span>Scanned</span><span>Action</span></div>{filtered.map(item => <div className="table-row" key={item.time}><LeafVisual className="thumb" /><div><b>{item.disease}</b><small>Leaf image analysis</small></div><div><b>Green Valley</b><small>{item.block}</small></div><b>{item.confidence}</b><Badge tone={item.tone}>{item.severity}</Badge><small>{item.time}</small><button className="row-more">•••</button></div>)}</section></> }

function Component1() {
  const [page, setPage] = useState('dashboard'); const [mobileOpen, setMobileOpen] = useState(false); const [role, setRole] = useState('Plantation Manager'); const [diagnosed, setDiagnosed] = useState(false)
  const pageTitles = useMemo(() => Object.fromEntries(navItems.map(item => [item[0], item[1]])), [])
  const navigate = next => { setPage(next); setMobileOpen(false); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const renderPage = () => { if (page === 'dashboard') return <Dashboard onNavigate={navigate} />; if (page === 'detect') return diagnosed ? <Diagnosis onNavigate={navigate} /> : <Detection onResult={() => setDiagnosed(true)} />; if (page === 'climate') return <Climate />; if (page === 'spread') return <Spread onNavigate={navigate} />; if (page === 'location') return <Location />; if (page === 'recommendations') return <Recommendations />; if (page === 'alerts') return <Alerts />; return <History /> }
  return <div className="app-shell"><aside className={`sidebar ${mobileOpen ? 'open' : ''}`}><div className="brand"><a href="/home" className="brand-mark"><img src="/teawise-logo.png" alt="TeaCore logo" /></a><a href="/home"><b>TeaCore</b><small>TEA INTELLIGENCE</small></a><button className="mobile-close" onClick={() => setMobileOpen(false)}>×</button></div><div className="sidebar-label">Workspace</div><nav>{navItems.map(([id, label, icon]) => <button className={page === id || (page === 'detect' && id === 'detect' && diagnosed) ? 'selected' : ''} onClick={() => navigate(id)} key={id}><span>{icon}</span>{label}{id === 'alerts' && <i className="nav-count">2</i>}</button>)}</nav><div className="sidebar-bottom"><label className="role-label">Viewing as<select value={role} onChange={e => setRole(e.target.value)}><option>Plantation Manager</option><option>Field Officer</option><option>Farmer</option><option>Agronomist / Researcher</option><option>Administrator</option></select></label><button>⚙ Settings</button><button>↪ Sign out</button><div className="user-mini"><span className="avatar">AM</span><span><b>Amaya M.</b><small>{role}</small></span><span>•••</span></div></div></aside><div className="mobile-scrim" onClick={() => setMobileOpen(false)} /><main className="main-area"><header className="topbar"><button className="mobile-menu" onClick={() => setMobileOpen(true)}>☰</button><div className="breadcrumb"><span>Workspace</span><b>/</b><strong>{pageTitles[page] || 'Diagnosis result'}</strong></div><div className="top-actions"><label className="plantation-select">⌖<select><option>Green Valley Tea Estate</option><option>Horton Plains Estate</option></select><span>⌄</span></label><button className="top-icon">⌕</button><button className="top-icon notification">♧<i /></button><span className="top-avatar">AM</span></div></header><div className="page-content">{renderPage()}</div><footer><span>TEACORE / TEA INTELLIGENCE</span><span>Prototype environment · Data simulated for research demonstration</span></footer></main></div>
}

export { Location, Recommendations, Alerts, History }

export default Component1
