import { useState } from 'react'
import Header from '../layout/Header'
import Footer from '../layout/Footer'

function PlantationHealth() {
  const [analysed, setAnalysed] = useState(false)

  return <main className="min-h-screen bg-slate-50 font-sans text-emerald-950">
    <Header />
    <div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-8 md:px-8"><div><p className="text-xs font-bold tracking-[.2em] text-lime-700">STEP 02 / PLANTATION INTELLIGENCE</p><h1 className="mt-2 font-serif text-3xl font-semibold text-emerald-950 md:text-4xl">Plantation health assessment</h1></div><div className="hidden rounded-full border border-emerald-200 bg-white px-4 py-2 text-xs font-bold text-emerald-700 sm:block">● AI engine ready</div></div>
    <section className="ph-workspace"><div className="ph-panel ph-inputs"><div className="ph-panel-title"><div><small>STEP 01</small><h2>Tell us about your field</h2></div><span>INPUTS</span></div><label className="upload"><input type="file" accept="image/*" /><span className="upload-icon">⌁</span><strong>Upload plantation image</strong><small>PNG, JPG or WEBP · Max 10MB</small></label><div className="ph-fields"><label>Temperature <div><input defaultValue="21" type="number" /><b>°C</b></div></label><label>Rainfall <div><input defaultValue="150" type="number" /><b>mm</b></div></label><label>Humidity <div><input defaultValue="82" type="number" /><b>%</b></div></label><label>Wind speed <div><input defaultValue="8" type="number" /><b>km/h</b></div></label><label>Solar radiation <div><select defaultValue="Moderate"><option>Low</option><option>Moderate</option><option>High</option></select></div></label></div><button className="ph-analyse" onClick={() => setAnalysed(true)}>{analysed ? 'Analysis complete ✓' : 'Run AI assessment  →'}</button></div><div className="ph-panel ph-results"><div className="ph-panel-title"><div><small>STEP 02</small><h2>AI health assessment</h2></div><span>OUTPUTS</span></div><div className="score"><div className="score-ring"><strong>{analysed ? '91' : '—'}</strong><small>/ 100</small></div><div><small>PLANTATION HEALTH SCORE</small><h3>{analysed ? 'Healthy & stable' : 'Awaiting analysis'}</h3><p>{analysed ? 'Your field is showing strong growth conditions.' : 'Add your field data and run the assessment.'}</p></div></div><div className="stress-list"><div><span>☀</span><label>Heat stress</label><b className="low">{analysed ? 'Low' : '—'}</b></div><div><span>💧</span><label>Water stress</label><b className="medium">{analysed ? 'Medium' : '—'}</b></div><div><span>☁</span><label>Rainfall stress</label><b className="low">{analysed ? 'Low' : '—'}</b></div><div><span>◉</span><label>Early warning</label><b className="safe">{analysed ? 'No immediate risk' : '—'}</b></div></div></div></section>
    <section className="ph-recommend"><div><p className="ph-kicker">ACTIONABLE GUIDANCE</p><h2>What should you do next?</h2><p>Practical, zone-specific recommendations generated from your plantation conditions.</p></div><div className="recommend-card"><div><span className="rec-icon">💧</span><div><strong>Monitor soil moisture</strong><p>Schedule irrigation if no rainfall occurs within the next 2–3 days.</p></div></div><div><span className="rec-icon">☘</span><div><strong>Maintain green coverage</strong><p>Keep shade cover and mulch in affected blocks to protect soil moisture.</p></div></div><div><span className="rec-icon">☁</span><div><strong>Watch rainfall patterns</strong><p>Improve drainage during periods of excess rainfall to reduce disease risk.</p></div></div></div></section>
    <Footer />
  </main>
}

export default PlantationHealth
